[build-system]
requires = ["setuptools>=42", "wheel>=0.37"]
build-backend = "setuptools.build_meta"

[project]
name = "drf-ip-restrictions"
version = "1.1.0"
description = "A library that allows IP restrictions for views/endpoints in Django REST framework."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]


dependencies = [
    "django>=4.2,<5.2",
    "djangorestframework>=3.15,<4",
    "django-filter>=24.3,<25",
    "django-ipware>=7.0.1,<7.1",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.0.1,<4.1",
]


[project.urls]
Homepage = "https://github.com/anexia/drf-ip-restrictions"
Repository = "https://github.com/anexia/drf-ip-restrictions"

[tool.ruff]
line-length = 120
respect-gitignore = true
extend-exclude = [".venv", "__pycache__"]
show-fixes = true

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["A", "B", "C", "E", "F", "I", "W", "T20", "LOG", "UP", "RUF010", "RUF019"]
ignore = ["E203", "E266", "E501", "F403", "F405"]

[tool.ruff.lint.isort]
known-first-party = ["drf-attachment"]
section-order = [
    "future",
    "standard-library",
    "django",
    "djangorestframework",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]
"djangorestframework" = ["rest_framework"]

[tool.ruff.lint.per-file-ignores]
"apps.py" = ["F401"]
